description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: "3.9"
    description: >
      Pick a specific circleci/python image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
